models/Gallery.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "gallery".
 *
 * @property integer $id
 * @property string $name
 * @property string $created_time
 * @property integer $likes
 * @property string $source
 *
 * @author Lidiexy Alonso <lidiexy@gmail.com>
 * @link https://bitbucket.org/lidiexy/fbtaskbe/
 */
class Gallery extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName(){
        return 'gallery';
    }

    /**
     * @inheritdoc
     */
    public function rules(){
        return [
            [['id', 'created_time', 'source'], 'required'],
            [['id', 'likes'], 'integer'],
            [['created_time'], 'safe'],
            [['source'], 'string'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels(){
        return [
            'id' => 'ID',
            'name' => 'Name',
            'created_time' => 'Created Time',
            'likes' => 'Likes',
            'source' => 'Source',
        ];
    }

    /**
     * Add new Photo from Json Data
     * Json data must have all fields, but the likes need special structure
     * eg: likes.summary.total_count
     *
     * @param array $data
     * @return bool If success
     */
    public function addNewPhoto($data = []){
        $this->id = $data['id'];
        $this->name = (isset($data['name']) && !empty($data['name'])) ? $data['name'] : 'Vanderbilt University';
        $this->created_time = $data['created_time'];
        $this->source = $data['source'];
        $this->likes = $data['likes']['summary']['total_count'];
        //save(false) permit avoid trigger events
        if ($this->save(false)){
            return true;
        }
        return false;
    }
}

controllers/GalleryController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\models\Gallery;
use app\models\SearchGallery;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * GalleryController implements the CRUD actions for Gallery model.
 */
class GalleryController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create'],
                'rules' => [
                    [
                        'actions' => ['create'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Show search page for the user... this action wait to load all data
     * @return mixed
     */
    public function actionSearchmore() {
        return $this->render('searchmore');
    }

    /**
     * Lists all Gallery models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SearchGallery();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Gallery model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Gallery model. Not recomended, cause the insertion process could be Automatic.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Gallery();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Gallery model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Gallery model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Gallery model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Gallery the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Gallery::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/LoaderController.php
<?php

namespace app\controllers;

use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;
use linslin\yii2\curl;
use app\models\FbRequest;
use app\models\Gallery;


class LoaderController extends Controller  {

    public function actions(){
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Insert all the new images in the Vanderbilt University FaceBook Page
     *
     * @param array $values_to_insert
     * @param array $array_from
     * @return bool
     * @throws \yii\db\Exception
     */
    private function insertNewPhotos($values_to_insert = [], $array_from = []){
        $data = [];
        $array_result = [];
        $doit = null;
        if(count($values_to_insert) > 0 && count($array_from) > 0) {
            foreach($values_to_insert as $obj){
                $data['id'] = $obj;
                $data['name'] = $array_from[$obj]['name'];
                $data['created_time'] = $array_from[$obj]['created_time'];
                $data['source'] = $array_from[$obj]['source'];
                $data['likes'] = $array_from[$obj]['likes'];
                $array_result[] = $data;
            }
            $doit = Yii::$app->db->createCommand()->batchInsert(Gallery::tableName(),array_keys($data), $array_result)->execute();
        }
        if(isset($doit) && !empty($doit)) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Remove all the images that had been erased from Vanderbilt University FaceBook Page
     *
     * @param array $values_to_remove
     * @return bool
     */
    private function removeErasedPhotos($values_to_remove = []) {
        if(sizeof($values_to_remove) > 0) {
            foreach($values_to_remove as $id) {
                $model = Gallery::findOne($id);
                if(isset($model)) {
                    $model->delete(false);
                }
            }
            return true;
        } else {
            return false;
        }
    }

    /**
     * Loader Action is the trigger to wrap all images from Vanderbilt University FaceBook Page
     * If this function would be part of one CRON task, the first conditional must be removed.
     * @return string jSON Result
     */
    public function actionLoader() {
        if (Yii::$app->request->isAjax) { //Erase this condition if need run this function directly
            //Init curl
            $curl = new curl\Curl();
            //Init Facebook Graph API request to obtain the default URL
            $request = new FbRequest();
            //Get the full array from the Grpah API, the url configured it's passed as a param.
            $array_fb_full = $request->facebookIdToArray($curl, $request->getDefaultPath());
            //Get the array of keys (ids) to calculate A diff B (rows to be added)
            $array_fb_ids = array_keys($array_fb_full);
            //Get the array of keys (ids) to calculate B diff A (rows to be removed)
            $array_model_ids = ArrayHelper::getColumn(
                Gallery::find()->select('id')->asArray()->all(),
                'id'
            );
            //A diff B (rows to be added)
            $values_to_insert = array_diff($array_fb_ids, $array_model_ids);
            //B diff A (rows to be removed)
            $values_to_remove = array_diff($array_model_ids, $array_fb_ids);
            //Process the values to insert and remove from Model Gallery
            if (sizeof($values_to_insert) > 0) {
                $this->insertNewPhotos($values_to_insert, $array_fb_full);
            }

            if (sizeof($values_to_remove) > 0) {
                $this->removeErasedPhotos($values_to_remove);
            }

            return Json::encode(['success' => true, 'message' => 'Process have been done']);
        }
    }

}

views/gallery/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Gallery */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="gallery-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_time')->textInput() ?>

    <?= $form->field($model, 'likes')->textInput() ?>

    <?= $form->field($model, 'source')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/gallery/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SearchGallery */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="gallery-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'created_time') ?>

    <?= $form->field($model, 'likes') ?>

    <?= $form->field($model, 'source') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/gallery/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Gallery */

$this->title = 'Create New Image (admin only)';
$this->params['breadcrumbs'][] = ['label' => 'Gallery index', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="gallery-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/gallery/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\SearchGallery */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Facebook - Vanderbilt Photo Gallery';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="gallery-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <div class="form-group">
        <?php
        if($dataProvider->count > 0) {
            echo Html::a('Search for more images', ['searchmore'], ['class' => 'btn btn-success']);
        } else {
            echo Html::a('Start the data process', ['searchmore'], ['class' => 'btn btn-success']);
        }
        ?>
        <?= Html::a('Create Image (Not Recomended)', ['create'], ['class' => 'btn btn-warning']); ?>
    </div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'created_time:datetime',
            'likes',
            [
                'attribute' => 'source',
                'format'=>'raw',
                'value'=>function($data) {
                    return Html::a('URL to image',$data->source,['target'=>'_blank']);
                }
            ],
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

views/gallery/searchmore.php
<?php
use yii\helpers\Url;

$this->title = 'Processing... the Vanderbilt Photo Gallery';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-index">

    <div class="jumbotron">
        <img src="images/vanderbilt-logo.jpg" class="img-circle" alt="Vanderbilt University" title="Vanderbilt University"/>
        <h1>Processing...!!!</h1>
        <p class="help-block">Please, wait until the process ends. You will be redirected after that.</p>
        <div id="spinner">
            <img src="images/loading_nobg.gif" alt="loading..." title="loading..."/>
        </div>
    </div>
</div>

<script>
window.onload = function(){
    $.ajax({
        type: 'get',
        dataType: 'json',
        //async: false,
        url: '<?= Url::to(['loader/loader']); ?>'
    }).success(function(data){
        if(data.success) {
            $('#spinner').html('<div class="alert alert-success">Process complete, Congratulation!!.</div>');
            setTimeout(function() {
                window.location.href = '<?= Url::to(['index']); ?>';
            }, 1000);
        } else {
            $('#spinner').html('<div class="alert alert-danger">ERROR in the process!! Sorry.</div>');
            setTimeout(function() {
                window.location.href = '<?= Url::to(['index']); ?>';
            }, 2000);
        }
    }).error(function(){
        $('#spinner').html('<div class="alert alert-danger">ERROR in the process!! Sorry.</div>');
        setTimeout(function() {
            window.location.href = '<?= Url::to(['index']); ?>';
        }, 1000);
    });
};
</script>

views/gallery/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Gallery */

$this->title = 'Update Image Data: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Gallery index', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="gallery-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/gallery/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Gallery */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Gallery Index', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="gallery-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'created_time',
            'likes',
            'source:ntext',
        ],
    ]) ?>

    <div class="clearfix">
        <img src="<?= $model->source; ?>" alt="<?= $model->name; ?>" title="<?= $model->name; ?>"/>
    </div>

</div>